"""fixed the db

Revision ID: 23af406ebc96
Revises: 7c46b74ebee8
Create Date: 2025-12-29 11:33:30.940648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23af406ebc96'
down_revision: Union[str, Sequence[str], None] = '7c46b74ebee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('projects_owner_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'owner_id')
    op.add_column('tasks', sa.Column('text', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('score', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'completed')
    op.add_column('users', sa.Column('t_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_foreign_key(None, 'users', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'project_id')
    op.drop_column('users', 't_score')
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'score')
    op.drop_column('tasks', 'text')
    op.add_column('projects', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('projects_owner_id_fkey'), 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
