"""V12

Revision ID: 5040fbba0e18
Revises: ffcb36155461
Create Date: 2026-01-07 17:29:08.748792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5040fbba0e18'
down_revision: Union[str, Sequence[str], None] = 'ffcb36155461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('unique_default_task_per_stage'), table_name='tasks', postgresql_where='(is_default = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('unique_default_task_per_stage'), 'tasks', ['project_id', 'stage'], unique=True, postgresql_where='(is_default = true)')
    op.alter_column('tasks', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
