"""V5

Revision ID: b47bb4f21ed9
Revises: fcf4d8bce01c
Create Date: 2025-12-30 12:21:38.272589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b47bb4f21ed9'
down_revision: Union[str, Sequence[str], None] = 'fcf4d8bce01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_stage', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'current_stage')
    # ### end Alembic commands ###
