"""V9

Revision ID: dd18f099c5cb
Revises: 30312757f583
Create Date: 2026-01-01 14:01:26.556395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd18f099c5cb'
down_revision: Union[str, Sequence[str], None] = '30312757f583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_default', sa.Boolean(), nullable=True))
    
    
    op.execute(
        "UPDATE tasks SET is_default = FALSE WHERE is_default IS NULL"
    )

    # 3️⃣ Enforce NOT NULL
    op.alter_column(
        'tasks',
        'is_default',
        nullable=False
    )

    # 4️⃣ Enforce ONLY ONE default per (project_id, stage)
    op.execute("""
        CREATE UNIQUE INDEX unique_default_task_per_stage
        ON tasks (project_id, stage)
        WHERE is_default = true;
    """)    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    
    op.execute(
        "DROP INDEX IF EXISTS unique_default_task_per_stage"
    )    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_default')
    # ### end Alembic commands ###
