"""V4

Revision ID: fcf4d8bce01c
Revises: 23af406ebc96
Create Date: 2025-12-29 14:13:03.575282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf4d8bce01c'
down_revision: Union[str, Sequence[str], None] = '23af406ebc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('stage', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('keywords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'keywords')
    op.drop_column('tasks', 'stage')
    # ### end Alembic commands ###
